# Generated by Django 2.2.12 on 2020-05-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='publish',
        ),
    ]
