# Generated by Django 2.2.12 on 2020-05-20 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_service_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
