# Generated by Django 2.2.12 on 2020-05-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_service_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Text')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='shop.Service')),
            ],
            options={
                'verbose_name': 'MessageService',
                'verbose_name_plural': 'MessageServices',
            },
        ),
    ]
