# Generated by Django 2.2.12 on 2020-05-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_usermessageservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessageservice',
            name='service',
            field=models.CharField(max_length=50, verbose_name='Service'),
        ),
    ]
