# Generated by Django 2.2.12 on 2020-05-24 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200524_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessageservice',
            name='email',
        ),
        migrations.AddField(
            model_name='usermessageservice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
